// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdJcvZycmIBFKu0gfDuGxGqREElt91C_M',
    appId: '1:468464971509:web:b9cc1aa16f2d6a7b661fbc',
    messagingSenderId: '468464971509',
    projectId: 'projeto-cafeteria-6c9df',
    authDomain: 'projeto-cafeteria-6c9df.firebaseapp.com',
    storageBucket: 'projeto-cafeteria-6c9df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPHiiDEGzkbR3f4vcNvlsMSDHuAsNJxsA',
    appId: '1:468464971509:android:a23cbb3a88f9cb6a661fbc',
    messagingSenderId: '468464971509',
    projectId: 'projeto-cafeteria-6c9df',
    storageBucket: 'projeto-cafeteria-6c9df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOGAcZG21botruZGPXUPid4bAxTeruvEo',
    appId: '1:468464971509:ios:0c3b8392e2d7f017661fbc',
    messagingSenderId: '468464971509',
    projectId: 'projeto-cafeteria-6c9df',
    storageBucket: 'projeto-cafeteria-6c9df.firebasestorage.app',
    iosClientId: '468464971509-52lb241gue0rb3brp4uavj51dpurpou4.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoCafeteria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOGAcZG21botruZGPXUPid4bAxTeruvEo',
    appId: '1:468464971509:ios:0c3b8392e2d7f017661fbc',
    messagingSenderId: '468464971509',
    projectId: 'projeto-cafeteria-6c9df',
    storageBucket: 'projeto-cafeteria-6c9df.firebasestorage.app',
    iosClientId: '468464971509-52lb241gue0rb3brp4uavj51dpurpou4.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoCafeteria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdJcvZycmIBFKu0gfDuGxGqREElt91C_M',
    appId: '1:468464971509:web:a3542aa0913d66a6661fbc',
    messagingSenderId: '468464971509',
    projectId: 'projeto-cafeteria-6c9df',
    authDomain: 'projeto-cafeteria-6c9df.firebaseapp.com',
    storageBucket: 'projeto-cafeteria-6c9df.firebasestorage.app',
  );

}